// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MusicPlayground",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MusicPlayground",
            targets: ["AppModule"],
            bundleIdentifier: "Minkyeong-Choi.MusicPlayground",
            teamIdentifier: "4S9N87385A",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .box),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "This app needs access to the microphone to record your amazing performance."),
                .fileAccess(.moviesFolder, mode: .readWrite),
                .fileAccess(.musicFolder, mode: .readWrite),
                .fileAccess(.pictureFolder, mode: .readWrite),
                .fileAccess(.downloadsFolder, mode: .readWrite),
                .fileAccess(.userSelectedFiles, mode: .readWrite)
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)